package com.huangmaojie.duomall.order.mapper;

import com.huangmaojie.duomall.order.entity.GoodsParams;
import com.huangmaojie.duomall.order.entity.GoodsParamsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    long countByExample(GoodsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int deleteByExample(GoodsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int insert(GoodsParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int insertSelective(GoodsParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    List<GoodsParams> selectByExample(GoodsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    GoodsParams selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsParams record, @Param("example") GoodsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByExample(@Param("record") GoodsParams record, @Param("example") GoodsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_params
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByPrimaryKey(GoodsParams record);
}