package com.huangmaojie.duomall.order.mapper;

import com.huangmaojie.duomall.order.entity.Remarks;
import com.huangmaojie.duomall.order.entity.RemarksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemarksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    long countByExample(RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int deleteByExample(RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int insert(Remarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int insertSelective(Remarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    List<Remarks> selectByExampleWithBLOBs(RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    List<Remarks> selectByExample(RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    Remarks selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") Remarks record, @Param("example") RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Remarks record, @Param("example") RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByExample(@Param("record") Remarks record, @Param("example") RemarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByPrimaryKeySelective(Remarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Remarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbg.generated Sat Apr 25 03:37:26 CST 2020
     */
    int updateByPrimaryKey(Remarks record);
}