package com.huangmaojie.duomall.user.entity;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.shop_name
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.tags
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.discount
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Long sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.promotion
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String promotion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.params
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark_tag_color
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private String remarkTagColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remarks_count
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Long remarksCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_analyse
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Integer goodAnalyse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_create
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_modified
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.version
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.title
     *
     * @return the value of goods.title
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.title
     *
     * @param title the value for goods.title
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.shop_name
     *
     * @return the value of goods.shop_name
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.shop_name
     *
     * @param shopName the value for goods.shop_name
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.tags
     *
     * @return the value of goods.tags
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.tags
     *
     * @param tags the value for goods.tags
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.discount
     *
     * @return the value of goods.discount
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.discount
     *
     * @param discount the value for goods.discount
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale
     *
     * @return the value of goods.sale
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Long getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale
     *
     * @param sale the value for goods.sale
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setSale(Long sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.promotion
     *
     * @return the value of goods.promotion
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getPromotion() {
        return promotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.promotion
     *
     * @param promotion the value for goods.promotion
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setPromotion(String promotion) {
        this.promotion = promotion == null ? null : promotion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.params
     *
     * @return the value of goods.params
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.params
     *
     * @param params the value for goods.params
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark_tag_color
     *
     * @return the value of goods.remark_tag_color
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public String getRemarkTagColor() {
        return remarkTagColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark_tag_color
     *
     * @param remarkTagColor the value for goods.remark_tag_color
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setRemarkTagColor(String remarkTagColor) {
        this.remarkTagColor = remarkTagColor == null ? null : remarkTagColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remarks_count
     *
     * @return the value of goods.remarks_count
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Long getRemarksCount() {
        return remarksCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remarks_count
     *
     * @param remarksCount the value for goods.remarks_count
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setRemarksCount(Long remarksCount) {
        this.remarksCount = remarksCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_analyse
     *
     * @return the value of goods.good_analyse
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Integer getGoodAnalyse() {
        return goodAnalyse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_analyse
     *
     * @param goodAnalyse the value for goods.good_analyse
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setGoodAnalyse(Integer goodAnalyse) {
        this.goodAnalyse = goodAnalyse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_create
     *
     * @return the value of goods.gmt_create
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_create
     *
     * @param gmtCreate the value for goods.gmt_create
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_modified
     *
     * @return the value of goods.gmt_modified
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_modified
     *
     * @param gmtModified the value for goods.gmt_modified
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.version
     *
     * @return the value of goods.version
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.version
     *
     * @param version the value for goods.version
     *
     * @mbg.generated Sat Apr 25 14:09:46 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}