package com.huangmaojie.duomall.cart.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.status
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.gmt_create
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.gmt_modified
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.version
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.id
     *
     * @return the value of order_goods.id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.id
     *
     * @param id the value for order_goods.id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_id
     *
     * @return the value of order_goods.order_id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_id
     *
     * @param orderId the value for order_goods.order_id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_id
     *
     * @return the value of order_goods.goods_id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_id
     *
     * @param goodsId the value for order_goods.goods_id
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.status
     *
     * @return the value of order_goods.status
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.status
     *
     * @param status the value for order_goods.status
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.gmt_create
     *
     * @return the value of order_goods.gmt_create
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.gmt_create
     *
     * @param gmtCreate the value for order_goods.gmt_create
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.gmt_modified
     *
     * @return the value of order_goods.gmt_modified
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.gmt_modified
     *
     * @param gmtModified the value for order_goods.gmt_modified
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.version
     *
     * @return the value of order_goods.version
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.version
     *
     * @param version the value for order_goods.version
     *
     * @mbg.generated Sat Mar 28 13:25:12 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}