package com.huangmaojie.duomall.cart.entity;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goods_id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_price
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Double payPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_pay
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Boolean isPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_ship
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Boolean isShip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ship_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Date shipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ship_num
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private String shipNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_receipt
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Boolean isReceipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receipt_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Date receiptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_create
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_modified
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.version
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goods_id
     *
     * @return the value of orders.goods_id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goods_id
     *
     * @param goodsId the value for orders.goods_id
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_price
     *
     * @return the value of orders.pay_price
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Double getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_price
     *
     * @param payPrice the value for orders.pay_price
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setPayPrice(Double payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_pay
     *
     * @return the value of orders.is_pay
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Boolean getIsPay() {
        return isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_pay
     *
     * @param isPay the value for orders.is_pay
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setIsPay(Boolean isPay) {
        this.isPay = isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_time
     *
     * @return the value of orders.pay_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_time
     *
     * @param payTime the value for orders.pay_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_ship
     *
     * @return the value of orders.is_ship
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Boolean getIsShip() {
        return isShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_ship
     *
     * @param isShip the value for orders.is_ship
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setIsShip(Boolean isShip) {
        this.isShip = isShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ship_time
     *
     * @return the value of orders.ship_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Date getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ship_time
     *
     * @param shipTime the value for orders.ship_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setShipTime(Date shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ship_num
     *
     * @return the value of orders.ship_num
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public String getShipNum() {
        return shipNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ship_num
     *
     * @param shipNum the value for orders.ship_num
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setShipNum(String shipNum) {
        this.shipNum = shipNum == null ? null : shipNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_receipt
     *
     * @return the value of orders.is_receipt
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Boolean getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_receipt
     *
     * @param isReceipt the value for orders.is_receipt
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setIsReceipt(Boolean isReceipt) {
        this.isReceipt = isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receipt_time
     *
     * @return the value of orders.receipt_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Date getReceiptTime() {
        return receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receipt_time
     *
     * @param receiptTime the value for orders.receipt_time
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setReceiptTime(Date receiptTime) {
        this.receiptTime = receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_create
     *
     * @return the value of orders.gmt_create
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_create
     *
     * @param gmtCreate the value for orders.gmt_create
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_modified
     *
     * @return the value of orders.gmt_modified
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_modified
     *
     * @param gmtModified the value for orders.gmt_modified
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.version
     *
     * @return the value of orders.version
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.version
     *
     * @param version the value for orders.version
     *
     * @mbg.generated Sat Apr 25 03:37:41 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}