package com.huangmaojie.duomall.goods.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.cellphone
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String cellphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Login_password
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.payment_password
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String paymentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.birthday
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_product_manager
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private Boolean isProductManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_logistic_manager
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private Boolean isLogisticManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gmt_create
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gmt_modified
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.version
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.cellphone
     *
     * @return the value of users.cellphone
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.cellphone
     *
     * @param cellphone the value for users.cellphone
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Login_password
     *
     * @return the value of users.Login_password
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Login_password
     *
     * @param loginPassword the value for users.Login_password
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.payment_password
     *
     * @return the value of users.payment_password
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getPaymentPassword() {
        return paymentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.payment_password
     *
     * @param paymentPassword the value for users.payment_password
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setPaymentPassword(String paymentPassword) {
        this.paymentPassword = paymentPassword == null ? null : paymentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatar
     *
     * @return the value of users.avatar
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatar
     *
     * @param avatar the value for users.avatar
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.birthday
     *
     * @return the value of users.birthday
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.birthday
     *
     * @param birthday the value for users.birthday
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_product_manager
     *
     * @return the value of users.is_product_manager
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Boolean getIsProductManager() {
        return isProductManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_product_manager
     *
     * @param isProductManager the value for users.is_product_manager
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setIsProductManager(Boolean isProductManager) {
        this.isProductManager = isProductManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_logistic_manager
     *
     * @return the value of users.is_logistic_manager
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Boolean getIsLogisticManager() {
        return isLogisticManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_logistic_manager
     *
     * @param isLogisticManager the value for users.is_logistic_manager
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setIsLogisticManager(Boolean isLogisticManager) {
        this.isLogisticManager = isLogisticManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_create
     *
     * @return the value of users.gmt_create
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_create
     *
     * @param gmtCreate the value for users.gmt_create
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_modified
     *
     * @return the value of users.gmt_modified
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_modified
     *
     * @param gmtModified the value for users.gmt_modified
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.version
     *
     * @return the value of users.version
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.version
     *
     * @param version the value for users.version
     *
     * @mbg.generated Sat Apr 25 03:37:33 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}