server:
  port: 8801 #运行端口号
spring:
  application:
    name: duomall-cart-server #服务名称
  datasource:
    name: duomall-user
    # 连接池类型，druid连接池springboot暂无法默认支持，需要自己配置bean
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.102.181:3306/duomall?serverTimezone=Hongkong
    username: root
    password: root
    # druid相关配置
    druid:
      # 初始化时建立物理连接的个数。
      initial-size: 5
      # 最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 3000
      # 是否缓存preparedStatement，也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: -1
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
#      min-evictable-idle-time-millis: 300000
#      max-evictable-idle-time-millis: 400000
      # 监控统计的stat,以及防sql注入的wall,         stat,wall,logback
      filters: stat
      #Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.web.springbootdruid.service.*
      # 是否启用StatViewServlet默认值true
      # 需要账号密码才能访问控制台，默认为root
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # IP白名单
        allow: 127.0.0.1
        # &emsp;IP黑名单（共同存在时，deny优先于allow）
        deny:
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/extension/*.xml
  type-aliases-package: com.huangmaojie.duomall.cart.entity
  config-location: classpath:mybatis-config.xml
eureka:
  instance:
    #    prefer-ip-address: true   #以IP地址注册到服务中心，相互注册使用IP地址
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 5
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    # 默认为90秒
    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    # 该值至少应该大于 leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 10
    #    设置使用ip
    prefer-ip-address: true
  #    设置外网IP号
  #    ip-address: 47.94.204.116
  #    设置外网端口号
  #    non-secure-port: 8701
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8705/eureka/
      defaultZone: http://118.31.102.181:8704/eureka/
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql

